'use strict';

/* exported appSettings */
var appSettings = {
    'WWW_URL': '@@WWW_URL',
    'API_URL': '@@API_URL',

    // Cloudinary settings
    'CLOUDINARY_CLOUD_NAME': '@@CLOUDINARY_CLOUD_NAME',

    'GOOGLE_CLIENT_ID': '@@GOOGLE_CLIENT_ID',
    'FACEBOOK_APP_ID': '@@FACEBOOK_APP_ID',
    'SOUNDCLOUD_CLIENT_ID': '@@SOUNDCLOUD_CLIENT_ID',
    'TWITTER_CLIENT_ID': '@@TWITTER_CLIENT_ID',


    'PUBLIC_FACEBOOK_ANALYSIS_ACCESS_KEY': '@@PUBLIC_FACEBOOK_ANALYSIS_ACCESS_KEY',
    'PUBLIC_FACEBOOK_ANALYSIS_SECRET_KEY': '@@PUBLIC_FACEBOOK_ANALYSIS_SECRET_KEY',
    'PUBLIC_FACEBOOK_BUCKET': '@@PUBLIC_FACEBOOK_BUCKET',
    'PUBLIC_FACEBOOK_REGION': '@@PUBLIC_FACEBOOK_REGION'
};
