'use strict';

/* exported appSettings */
var appSettings = {
    'WWW_URL': '@@WWW_URL',
    'API_URL': '@@API_URL',

    'CLOUDINARY_CLOUD_NAME': '@@CLOUDINARY_CLOUD_NAME',

    'GOOGLE_CLIENT_ID': '@@GOOGLE_CLIENT_ID',
    'FACEBOOK_APP_ID': '@@FACEBOOK_APP_ID',
    'SOUNDCLOUD_CLIENT_ID': '@@SOUNDCLOUD_CLIENT_ID',

    'TWITTER_CONSUMER_KEY': '@@TWITTER_CONSUMER_KEY',
    'TWITTER_CONSUMER_SECRET': '@@TWITTER_CONSUMER_SECRET',
    'TWITTER_CONCATENTATED_AUTH_STRING': '@@TWITTER_CONCATENTATED_AUTH_STRING',
    'TWITTER_ACCESS_TOKEN': '@@TWITTER_ACCESS_TOKEN',
    'TWITTER_ACCESS_TOKEN_SECRET': '@@TWITTER_ACCESS_TOKEN_SECRET',

    'OAUTH_PUBLIC_KEY': '@@OAUTH_PUBLIC_KEY',
    'OAUTH_SECRET_KEY': '@@OAUTH_SECRET_KEY', 

    'PUBLIC_FACEBOOK_REGION': '@@PUBLIC_FACEBOOK_REGION',
    'PUBLIC_FACEBOOK_ANALYSIS_ACCESS_KEY': '@@PUBLIC_FACEBOOK_ANALYSIS_ACCESS_KEY',
    'PUBLIC_FACEBOOK_BUCKET': '@@PUBLIC_FACEBOOK_BUCKET',
};
